services:
  - type: static
    name: vaccination-tracker-frontend
    buildCommand: npm install && CI=false npm run build
    publishDir: build
    staticPublishPath: /
    envVars:
      - key: NODE_VERSION
        value: 16.x
      - key: NODE_ENV
        value: production
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: no-cache