services:
  - type: web
    name: vaccination-tracker-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 16.x
      - key: CI
        value: false