services:
  - type: static
    name: vaxtrack-frontend
    runtime: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    publishDir: build
    staticPublishPath: /
    env: node
    nodeVersion: 16
    buildFilter:
      ignoredPaths:
        - node_modules/**