services:
  - type: web
    name: vaxtrak-app
    env: static
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    publishDir: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html